stages:          # List of stages for jobs, and their order of execution
  - build

build_account_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd account-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/account-service-0.0.1-SNAPSHOT.jar
build_inventory_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd inventory-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/inventory-service-0.0.1-SNAPSHOT.jar


build_facility_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd facility-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/facility-service-0.0.1-SNAPSHOT.jar
      -