stages:          # List of stages for jobs, and their order of execution
  - build
  - docker

build_account_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd account-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/account-service-0.0.1-SNAPSHOT.jar
build_inventory_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd inventory-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/inventory-service-0.0.1-SNAPSHOT.jar


build_facility_service:
  stage: build
  image: gradle:8.10.2-jdk11
  script:
    - cd facility-service
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/facility-service-0.0.1-SNAPSHOT.jar
variables:
  DOCKER_USERNAME: "nathanielravindra"

docker_build_account_service:
    stage: docker
    image: docker:latest
    script:
      - docker build -f account.Dockerfile -t $DOCKER_USERNAME/account-service:latest account-service/
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/account-service:latest

docker_build_inventory_service:
  stage: docker
  image: docker:latest
  script:
    - docker build -f inventory.Dockerfile -t $DOCKER_USERNAME/inventory-service:latest inventory-service/
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/inventory-service:latest
docker_build_facility_service:
  stage: docker
  image: docker:latest
  script:
    - docker build -f facility.Dockerfile -t $DOCKER_USERNAME/facility-service:latest facility-service/
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/facility-service:latest