apiVersion: v1
kind: ConfigMap
metadata:
  name: db-galera-init
  namespace: default
data:
  galera-init.sh: |
    #!/bin/bash

    # Check if grastate.dat exists (used to determine first node or member node)
    if [ ! -f /var/lib/mysql/grastate.dat ]; then
        echo "Initializing the first node of the Galera cluster"
        
        # Start MariaDB with the Galera options and initialize the first node
        mysqld --wsrep-new-cluster --user=mysql &
        
        # Wait for MariaDB to start
        until mysqladmin ping --silent; do
            echo "Waiting for MariaDB to start..."
            sleep 1
        done
        
        # Stop and restart MariaDB normally
        echo "Cluster initialized, starting MariaDB normally"
        kill $(cat /var/run/mysqld/mysqld.pid)
        mysqld --user=mysql
    else
        echo "Joining the cluster"
        mysqld --user=mysql
    fi