name: Docker Deploy
on: push

jobs:
  build_account_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: |
          cd account-service
          chmod +x ./gradlew
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build Account Service
        run: |
          cd account-service
          ./gradlew clean
          ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          docker build -f account.Dockerfile -t nathanielravindra/account-service:latest ./account-service

      - name: Push Docker image to Docker Hub
        run: |
          docker push nathanielravindra/account-service:latest

  build_inventory_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Build Inventory Service
        run: |
          cd inventory-service
          ./gradlew clean build
      - name: Upload Inventory Service Artifact
        uses: actions/upload-artifact@v3
        with:
          name: inventory-service-jar
          path: inventory-service/build/libs/inventory-service-0.0.1-SNAPSHOT.jar

  build_facility_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Build Facility Service
        run: |
          cd facility-service
          ./gradlew clean build
      - name: Upload Facility Service Artifact
        uses: actions/upload-artifact@v3
        with:
          name: facility-service-jar
          path: facility-service/build/libs/facility-service-0.0.1-SNAPSHOT.jar
