name: docker-deploy
on: push
# on:   
#   workflow_run:
#     workflows: ["see-deploy"]
#     types:
#       - completed

jobs:
  build_account_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: |
          cd account-service
          chmod +x ./gradlew
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build Account Service
        run: |
          cd account-service
          ./gradlew clean
          ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          cd account-service
          docker build -f account.Dockerfile -t nathanielravindra/account-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nathanielravindra/account-service:latest

  build_inventory_service:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: |
          cd inventory-service
          chmod +x ./gradlew
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build Inventory Service
        run: |
          cd inventory-service
          ./gradlew clean
          ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          cd inventory-service
          docker build -f inventory.Dockerfile -t nathanielravindra/inventory-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nathanielravindra/inventory-service:latest
          
  build_admin_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: |
          cd admin-service
          chmod +x ./gradlew
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build admin Service
        run: |
          cd admin-service
          ./gradlew clean
          ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          cd admin-service
          docker build -f admin.Dockerfile -t nathanielravindra/admin-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nathanielravindra/admin-service:latest

  build_facility_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make gradlew executable
        run: |
          cd facility-service
          chmod +x ./gradlew
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build Facility Service
        run: |
          cd facility-service
          ./gradlew clean
          ./gradlew build --no-daemon

      - name: Build Docker image
        run: |
          cd facility-service
          docker build -f facility.Dockerfile -t nathanielravindra/facility-service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nathanielravindra/facility-service:latest
  deploy_nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build Docker image
      run: |
        docker build -f nginx.Dockerfile -t nathanielravindra/nginx-k8s:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push nathanielravindra/nginx-k8s:latest
    
