name: Load Test

on: push

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up k6
      run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

    - name: Login to k6 Cloud
      run: |
        echo ${{ secrets.K6_API_TOKEN }} | k6 cloud login --token

    - name: Run k6 load test
      run: |
        k6 cloud test-script.js
