name: Load Test

on:   
  workflow_run:
    workflows: ["k8s-deploy"]
    types:
      - completed
jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup K6
      uses: grafana/setup-k6-action@v1
    - name: Cache OpenConnect .deb Package
      uses: actions/cache@v4
      id: cache-openconnect
      with:
        path: ./packages
        key: ${{ runner.os }}-openconnect-${{ hashFiles('package-list.txt') }}
        restore-keys: |
          ${{ runner.os }}-openconnect-
    - name: Download OpenConnect Package
      if: steps.cache-openconnect.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./packages
        apt-get download openconnect
        mv openconnect_*.deb ./packages/
      shell: bash

    - name: Install OpenConnect from Cached Package
      run: |
        sudo dpkg -i ./packages/openconnect_*.deb || sudo apt-get install -f -y
        sudo /sbin/modprobe tun
      shell: bash

    - name: Install AnyConnect VPN & Login
      env:
        VPN_USERNAME: ${{ secrets.USERNAME }}
        VPN_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        printf 'Netlab Fontys ICT\n%s\n%s\n' "$VPN_USERNAME" "$VPN_PASSWORD" | sudo openconnect vpn.netlab.fontysict.nl -b
      shell: bash

    - name: Verify VPN Connection
      run: |
        ifconfig
        ping -c 4 ${{ secrets.IP_ADDRESS }}
      shell: bash

    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
        K6_CLOUD_PROJECT_ID: ${{ secrets.K6_PROJECT }}
      with:
        path: test-script.js
